import { useState } from 'react';
import { Link } from 'wouter';
import { FashionImage } from '../components/FashionImage';
import { Icon } from '../components/Icon';
import { localize, styleLabel, useLanguage } from '../lib/language';
import { isLookSaved, toggleSavedLook } from '../lib/savedLooks';
import { useProfileGender } from '../lib/profileGender';

const looks = [
  { title: 'Chocolate layers', style: 'Stockholm', position: '50% 100%', tall: true, image: '/assets/discover/stockholm/stockholm-01.jpg' },
  { title: 'Coffee and denim', style: 'Stockholm', position: '50% 0%', tall: false, image: '/assets/discover/stockholm/stockholm-02.jpg' },
  { title: 'Polka leather', style: 'Stockholm', position: '100% 0%', tall: true, image: '/assets/discover/stockholm/stockholm-03.jpg' },
  { title: 'Gallery afternoon', style: 'Stockholm', position: '0% 100%', tall: false, image: '/assets/discover/stockholm/stockholm-04.jpg' },
  { title: 'Cream and cocoa', style: 'Stockholm', position: '50% 100%', tall: true, image: '/assets/discover/stockholm/stockholm-05.jpg' },
  { title: 'Soft ivory', style: 'Stockholm', position: '100% 100%', tall: false, image: '/assets/discover/stockholm/stockholm-06.jpg' },
  { title: 'Black and silver', style: 'Stockholm', position: '0% 0%', tall: true, image: '/assets/discover/stockholm/stockholm-07.jpg' },
  { title: 'Midnight glow', style: 'Stockholm', position: '50% 0%', tall: false, image: '/assets/discover/stockholm/stockholm-midnight-glow.jpg' },
  { title: 'Nordic winter', style: 'Stockholm', position: '100% 0%', tall: true, image: '/assets/discover/stockholm/stockholm-09.jpg' },
  { title: 'Nordic cocoa', style: 'Stockholm', position: '0% 0%', tall: false, image: '/assets/discover/stockholm/stockholm-10.jpg' },
  { title: 'Golden braid', style: 'Stockholm', position: '50% 0%', tall: true, image: '/assets/discover/stockholm/stockholm-11.jpg' },
  { title: 'Blue daydream', style: 'Stockholm', position: '100% 0%', tall: false, image: '/assets/discover/stockholm/stockholm-12.jpg' },
  { title: 'Ivory ruffles', style: 'Stockholm', position: '0% 100%', tall: true, image: '/assets/discover/stockholm/stockholm-13.jpg' },
  { title: 'Cocoa mini', style: 'Stockholm', position: '50% 100%', tall: false, image: '/assets/discover/stockholm/stockholm-14.jpg' },
  { title: 'Midnight denim', style: 'Stockholm', position: '100% 100%', tall: true, image: '/assets/discover/stockholm/stockholm-15.jpg' },
  { title: 'Blush nordic', style: 'Stockholm', position: '0% 0%', tall: false, image: '/assets/discover/stockholm/stockholm-16.jpg' },
  { title: 'After-school layers', style: 'Downtown', position: '0% 0%', tall: true, image: '/assets/discover/downtown/downtown-01.jpg' },
  { title: 'Burgundy city', style: 'Downtown', position: '50% 0%', tall: false, image: '/assets/discover/downtown/downtown-02.jpg' },
  { title: 'Leather and flare', style: 'Downtown', position: '100% 0%', tall: true, image: '/assets/discover/downtown/downtown-03.jpg' },
  { title: 'Downtown comfort', style: 'Downtown', position: '0% 100%', tall: false, image: '/assets/discover/downtown/downtown-04.jpg' },
  { title: 'Weekend layers', style: 'Downtown', position: '50% 100%', tall: true, image: '/assets/discover/downtown/downtown-05.jpg' },
  { title: 'Brown plaid mood', style: 'Downtown', position: '100% 100%', tall: false, image: '/assets/discover/downtown/downtown-06.jpg' },
  { title: 'Teal city knit', style: 'Downtown', position: '0% 0%', tall: true, image: '/assets/discover/downtown/downtown-07.jpg' },
  { title: 'Monkey charm', style: 'Downtown', position: '50% 0%', tall: false, image: '/assets/discover/downtown/downtown-08.jpg' },
  { title: 'Rose academy', style: 'Downtown', position: '100% 0%', tall: true, image: '/assets/discover/downtown/downtown-09.jpg' },
  { title: 'Ivory city layers', style: 'Downtown', position: '0% 100%', tall: false, image: '/assets/discover/downtown/downtown-10.jpg' },
  { title: 'Plaid noir', style: 'Downtown', position: '50% 100%', tall: true, image: '/assets/discover/downtown/downtown-11.jpg' },
  { title: 'Striped teddy day', style: 'Downtown', position: '100% 100%', tall: false, image: '/assets/discover/downtown/downtown-12.jpg' },
  { title: 'Honey vintage', style: 'Downtown', position: '0% 0%', tall: true, image: '/assets/discover/downtown/downtown-13.jpg' },
  { title: 'Striped night', style: 'Downtown', position: '50% 0%', tall: false, image: '/assets/discover/downtown/downtown-14.jpg' },
  { title: 'Corduroy winter', style: 'Downtown', position: '100% 0%', tall: true, image: '/assets/discover/downtown/downtown-15.jpg' },
  { title: 'Downtown journal', style: 'Downtown', position: '0% 100%', tall: false, image: '/assets/discover/downtown/downtown-16.jpg' },
  { title: 'Pink rebel', style: 'Y2K', position: '0% 0%', tall: true, image: '/assets/discover/y2k/y2k-01.jpg' },
  { title: 'Aqua pop', style: 'Y2K', position: '50% 0%', tall: false, image: '/assets/discover/y2k/y2k-02.jpg' },
  { title: 'Princess energy', style: 'Y2K', position: '100% 0%', tall: true, image: '/assets/discover/y2k/y2k-03.jpg' },
  { title: 'Graphic denim', style: 'Y2K', position: '0% 100%', tall: false, image: '/assets/discover/y2k/y2k-04.jpg' },
  { title: 'Candy casual', style: 'Y2K', position: '50% 100%', tall: true, image: '/assets/discover/y2k/y2k-05.jpg' },
  { title: 'Chasing stars', style: 'Y2K', position: '0% 0%', tall: false, image: '/assets/discover/y2k/y2k-06.jpg' },
  { title: 'Silver fawn', style: 'Y2K', position: '50% 0%', tall: true, image: '/assets/discover/y2k/y2k-07.jpg' },
  { title: 'Preppy grunge', style: 'Y2K', position: '100% 0%', tall: false, image: '/assets/discover/y2k/y2k-08.jpg' },
  { title: 'Guitar grey', style: 'Y2K', position: '0% 100%', tall: true, image: '/assets/discover/y2k/y2k-09.jpg' },
  { title: 'Union rebel', style: 'Y2K', position: '50% 100%', tall: false, image: '/assets/discover/y2k/y2k-10.jpg' },
  { title: 'Pink archive', style: 'Y2K', position: '100% 100%', tall: true, image: '/assets/discover/y2k/y2k-11.jpg' },
  { title: 'Crimson butterfly', style: 'Y2K', position: '0% 0%', tall: false, image: '/assets/discover/y2k/y2k-12.jpg' },
  { title: 'Silver star denim', style: 'Y2K', position: '50% 0%', tall: true, image: '/assets/discover/y2k/y2k-13.jpg' },
  { title: 'Blue cyber', style: 'Y2K', position: '100% 0%', tall: false, image: '/assets/discover/y2k/y2k-14.jpg' },
  { title: 'Burgundy star', style: 'Y2K', position: '0% 100%', tall: true, image: '/assets/discover/y2k/y2k-15.jpg' },
  { title: 'New York star', style: 'Y2K', position: '50% 100%', tall: false, image: '/assets/discover/y2k/y2k-16.jpg' },
  { title: 'Camel tailoring', style: 'Old Money', position: '0% 0%', tall: true, image: '/assets/discover/old-money/old-money-01.jpg' },
  { title: 'Equestrian classic', style: 'Old Money', position: '50% 0%', tall: false, image: '/assets/discover/old-money/old-money-02.jpg' },
  { title: 'Chocolate and ivory', style: 'Old Money', position: '100% 0%', tall: true, image: '/assets/discover/old-money/old-money-03.jpg' },
  { title: 'Burgundy heritage', style: 'Old Money', position: '0% 100%', tall: false, image: '/assets/discover/old-money/old-money-04.jpg' },
  { title: 'Cream investment', style: 'Old Money', position: '50% 100%', tall: true, image: '/assets/discover/old-money/old-money-05.jpg' },
  { title: 'Navy polish', style: 'Old Money', position: '100% 100%', tall: false, image: '/assets/discover/old-money/old-money-06.jpg' },
  { title: 'Monochrome elegance', style: 'Old Money', position: '0% 0%', tall: true, image: '/assets/discover/old-money/old-money-07.jpg' },
  { title: 'Midnight baroque', style: 'Old Money', position: '50% 0%', tall: false, image: '/assets/discover/old-money/old-money-08.jpg' },
  { title: 'Italian espresso', style: 'Old Money', position: '100% 0%', tall: true, image: '/assets/discover/old-money/old-money-09.jpg' },
  { title: 'Riviera stripes', style: 'Old Money', position: '0% 100%', tall: false, image: '/assets/discover/old-money/old-money-10.jpg' },
  { title: 'Heritage plaid', style: 'Old Money', position: '50% 100%', tall: true, image: '/assets/discover/old-money/old-money-11.jpg' },
  { title: 'Gilded corset', style: 'Old Money', position: '100% 100%', tall: false, image: '/assets/discover/old-money/old-money-12.jpg' },
  { title: 'Vanilla reserve', style: 'Old Money', position: '0% 0%', tall: true, image: '/assets/discover/old-money/old-money-13.jpg' },
  { title: 'Leopard tailoring', style: 'Old Money', position: '50% 0%', tall: false, image: '/assets/discover/old-money/old-money-14.jpg' },
  { title: 'Navy maison', style: 'Old Money', position: '100% 0%', tall: true, image: '/assets/discover/old-money/old-money-15.jpg' },
  { title: 'Black reserve', style: 'Old Money', position: '0% 100%', tall: false, image: '/assets/discover/old-money/old-money-16.jpg' },
  { title: 'Pink lounge', style: 'Clean Girl', position: '0% 0%', tall: true, image: '/assets/discover/clean-girl/clean-girl-01.jpg' },
  { title: 'Blush denim', style: 'Clean Girl', position: '50% 0%', tall: false, image: '/assets/discover/clean-girl/clean-girl-02.jpg' },
  { title: 'Everyday neutral', style: 'Clean Girl', position: '100% 0%', tall: true, image: '/assets/discover/clean-girl/clean-girl-03.jpg' },
  { title: 'Soft morning', style: 'Clean Girl', position: '0% 100%', tall: false, image: '/assets/discover/clean-girl/clean-girl-04.jpg' },
  { title: 'Cozy clean', style: 'Clean Girl', position: '50% 100%', tall: true, image: '/assets/discover/clean-girl/clean-girl-05.jpg' },
  { title: 'Pink and denim', style: 'Clean Girl', position: '100% 100%', tall: false, image: '/assets/discover/clean-girl/clean-girl-06.jpg' },
  { title: 'Simple essentials', style: 'Clean Girl', position: '0% 0%', tall: true, image: '/assets/discover/clean-girl/clean-girl-07.jpg' },
  { title: 'Navy clean street', style: 'Clean Girl', position: '50% 0%', tall: false, image: '/assets/discover/clean-girl/clean-girl-08.jpg' },
  { title: 'Grey reset', style: 'Clean Girl', position: '100% 0%', tall: true, image: '/assets/discover/clean-girl/clean-girl-09.jpg' },
  { title: 'Silver wellness', style: 'Clean Girl', position: '0% 100%', tall: false, image: '/assets/discover/clean-girl/clean-girl-10.jpg' },
  { title: 'Pink pilates', style: 'Clean Girl', position: '50% 100%', tall: true, image: '/assets/discover/clean-girl/clean-girl-11.jpg' },
  { title: 'Blush campus', style: 'Clean Girl', position: '100% 100%', tall: false, image: '/assets/discover/clean-girl/clean-girl-12.jpg' },
  { title: 'Silver braid', style: 'Clean Girl', position: '0% 0%', tall: true, image: '/assets/discover/clean-girl/clean-girl-13.jpg' },
  { title: 'Blue bunny morning', style: 'Clean Girl', position: '50% 0%', tall: false, image: '/assets/discover/clean-girl/clean-girl-14.jpg' },
  { title: 'Quiet grey basics', style: 'Clean Girl', position: '100% 0%', tall: true, image: '/assets/discover/clean-girl/clean-girl-15.jpg' },
  { title: 'Vanilla ease', style: 'Clean Girl', position: '0% 100%', tall: false, image: '/assets/discover/clean-girl/clean-girl-16.jpg' },
  { title: 'Red campus', style: 'Street Style', position: '0% 0%', tall: true, image: '/assets/discover/street-style/street-style-01.jpg' },
  { title: 'Polo and denim', style: 'Street Style', position: '50% 0%', tall: false, image: '/assets/discover/street-style/street-style-02.jpg' },
  { title: 'Yellow statement', style: 'Street Style', position: '100% 0%', tall: true, image: '/assets/discover/street-style/street-style-03.jpg' },
  { title: 'Cherry sport', style: 'Street Style', position: '0% 100%', tall: false, image: '/assets/discover/street-style/street-style-04.jpg' },
  { title: 'Denim and red', style: 'Street Style', position: '100% 100%', tall: true, image: '/assets/discover/street-style/street-style-06.jpg' },
  { title: 'Pink street set', style: 'Street Style', position: '0% 0%', tall: false, image: '/assets/discover/street-style/street-style-07.jpg' },
  { title: 'Burgundy skate', style: 'Street Style', position: '50% 0%', tall: true, image: '/assets/discover/street-style/street-style-08.jpg' },
  { title: 'Grey street layers', style: 'Street Style', position: '100% 0%', tall: false, image: '/assets/discover/street-style/street-style-09.jpg' },
  { title: 'Black gold track', style: 'Street Style', position: '0% 100%', tall: true, image: '/assets/discover/street-style/street-style-10.jpg' },
  { title: 'Spider campus', style: 'Street Style', position: '50% 100%', tall: false, image: '/assets/discover/street-style/street-style-11.jpg' },
  { title: 'Green terrace', style: 'Street Style', position: '100% 100%', tall: true, image: '/assets/discover/street-style/street-style-12.jpg' },
  { title: 'Burgundy jersey', style: 'Street Style', position: '0% 0%', tall: false, image: '/assets/discover/street-style/street-style-13.jpg' },
  { title: 'Racing scarf', style: 'Street Style', position: '50% 0%', tall: true, image: '/assets/discover/street-style/street-style-14.jpg' },
  { title: 'Gold denim maxi', style: 'Street Style', position: '100% 0%', tall: false, image: '/assets/discover/street-style/street-style-15.jpg' },
  { title: 'New York blue', style: 'Street Style', position: '50% 100%', tall: true, image: '/assets/discover/street-style/street-style-17.jpg' },
  { title: 'Union denim', style: 'Street Style', position: '100% 100%', tall: false, image: '/assets/discover/street-style/street-style-18.jpg' },
  { title: 'Brown flare', style: 'Vintage', position: '0% 0%', tall: true, image: '/assets/discover/vintage/vintage-01.jpg' },
  { title: 'Plaid nostalgia', style: 'Vintage', position: '50% 0%', tall: false, image: '/assets/discover/vintage/vintage-02.jpg' },
  { title: 'Corduroy lace', style: 'Vintage', position: '100% 0%', tall: true, image: '/assets/discover/vintage/vintage-03.jpg' },
  { title: 'Printed denim', style: 'Vintage', position: '0% 100%', tall: false, image: '/assets/discover/vintage/vintage-04.jpg' },
  { title: 'Romantic archive', style: 'Vintage', position: '50% 100%', tall: true, image: '/assets/discover/vintage/vintage-05.jpg' },
  { title: 'Chocolate leather', style: 'Vintage', position: '100% 100%', tall: false, image: '/assets/discover/vintage/vintage-06.jpg' },
  { title: 'Retro traveler', style: 'Vintage', position: '0% 0%', tall: true, image: '/assets/discover/vintage/vintage-07.jpg' },
  { title: 'Autumn archive', style: 'Vintage', position: '50% 0%', tall: false, image: '/assets/discover/vintage/vintage-08.jpg' },
  { title: 'Retro brunette', style: 'Vintage', position: '100% 0%', tall: true, image: '/assets/discover/vintage/vintage-09.jpg' },
  { title: 'Cocoa flare', style: 'Vintage', position: '0% 100%', tall: false, image: '/assets/discover/vintage/vintage-10.jpg' },
  { title: 'Leather modernist', style: 'Vintage', position: '50% 100%', tall: true, image: '/assets/discover/vintage/vintage-11.jpg' },
  { title: 'Polka afternoon', style: 'Vintage', position: '100% 100%', tall: false, image: '/assets/discover/vintage/vintage-12.jpg' },
  { title: 'Plaid road trip', style: 'Vintage', position: '0% 0%', tall: true, image: '/assets/discover/vintage/vintage-13.jpg' },
  { title: 'Midnight polka', style: 'Vintage', position: '50% 0%', tall: false, image: '/assets/discover/vintage/vintage-14.jpg' },
  { title: 'Corset archive', style: 'Vintage', position: '100% 0%', tall: true, image: '/assets/discover/vintage/vintage-15.jpg' },
  { title: 'Cocoa weekend', style: 'Vintage', position: '0% 100%', tall: false, image: '/assets/discover/vintage/vintage-16.jpg' },
  { title: 'Pearl and lace', style: 'Coquette', position: '0% 0%', tall: true, image: '/assets/discover/coquette/coquette-01.jpg' },
  { title: 'Soft neutral', style: 'Coquette', position: '50% 0%', tall: false, image: '/assets/discover/coquette/coquette-02.jpg' },
  { title: 'Blush lounge', style: 'Coquette', position: '100% 0%', tall: true, image: '/assets/discover/coquette/coquette-03.jpg' },
  { title: 'Pink daydream', style: 'Coquette', position: '0% 100%', tall: false, image: '/assets/discover/coquette/coquette-04.jpg' },
  { title: 'Pink polka', style: 'Coquette', position: '50% 100%', tall: true, image: '/assets/discover/coquette/coquette-05.jpg' },
  { title: 'Floral pastel', style: 'Coquette', position: '100% 100%', tall: false, image: '/assets/discover/coquette/coquette-06.jpg' },
  { title: 'Winter ribbon', style: 'Coquette', position: '0% 0%', tall: true, image: '/assets/discover/coquette/coquette-07.jpg' },
  { title: 'Blush bellbottoms', style: 'Coquette', position: '50% 0%', tall: false, image: '/assets/discover/coquette/coquette-08.jpg' },
  { title: 'Pink snow day', style: 'Coquette', position: '100% 0%', tall: true, image: '/assets/discover/coquette/coquette-09.jpg' },
  { title: 'Shoujo ribbons', style: 'Coquette', position: '0% 100%', tall: false, image: '/assets/discover/coquette/coquette-10.jpg' },
  { title: 'Babydoll noir', style: 'Coquette', position: '50% 100%', tall: true, image: '/assets/discover/coquette/coquette-11.jpg' },
  { title: 'Crystal hearts', style: 'Coquette', position: '100% 100%', tall: false, image: '/assets/discover/coquette/coquette-12.jpg' },
  { title: 'Parisian doll', style: 'Coquette', position: '0% 0%', tall: true, image: '/assets/discover/coquette/coquette-13.jpg' },
  { title: 'Strawberry cream', style: 'Coquette', position: '50% 0%', tall: false, image: '/assets/discover/coquette/coquette-14.jpg' },
  { title: 'Miffy schoolgirl', style: 'Coquette', position: '100% 0%', tall: true, image: '/assets/discover/coquette/coquette-15.jpg' },
  { title: 'Ribbon diary', style: 'Coquette', position: '0% 100%', tall: false, image: '/assets/discover/coquette/coquette-16.jpg' },
  { title: 'Navy everyday', style: 'Casual', position: '0% 0%', tall: true, image: '/assets/discover/casual/casual-01.jpg' },
  { title: 'Coffee basics', style: 'Casual', position: '50% 0%', tall: false, image: '/assets/discover/casual/casual-02.jpg' },
  { title: 'Weekend stripe', style: 'Casual', position: '100% 0%', tall: true, image: '/assets/discover/casual/casual-03.jpg' },
  { title: 'Soft layers', style: 'Casual', position: '0% 100%', tall: false, image: '/assets/discover/casual/casual-04.jpg' },
  { title: 'Bookshop afternoon', style: 'Casual', position: '50% 100%', tall: true, image: '/assets/discover/casual/casual-05.jpg' },
  { title: 'Chocolate hoodie', style: 'Casual', position: '100% 100%', tall: false, image: '/assets/discover/casual/casual-06.jpg' },
  { title: 'Cozy neutral', style: 'Casual', position: '0% 0%', tall: true, image: '/assets/discover/casual/casual-07.jpg' },
  { title: 'Burgundy knit', style: 'Casual', position: '50% 0%', tall: false, image: '/assets/discover/casual/casual-08.jpg' },
  { title: 'Leather weekend', style: 'Casual', position: '100% 0%', tall: true, image: '/assets/discover/casual/casual-09.jpg' },
  { title: 'Leather and sambas', style: 'Casual', position: '0% 100%', tall: false, image: '/assets/discover/casual/casual-10.jpg' },
  { title: 'Cherry keychain', style: 'Casual', position: '50% 100%', tall: true, image: '/assets/discover/casual/casual-11.jpg' },
  { title: 'Cocoa stripe', style: 'Casual', position: '100% 100%', tall: false, image: '/assets/discover/casual/casual-12.jpg' },
  { title: 'Pistachio denim', style: 'Casual', position: '0% 0%', tall: true, image: '/assets/discover/casual/casual-13.jpg' },
  { title: 'Library layers', style: 'Casual', position: '50% 0%', tall: false, image: '/assets/discover/casual/casual-14.jpg' },
  { title: 'Cherry dots', style: 'Casual', position: '100% 0%', tall: true, image: '/assets/discover/casual/casual-15.jpg' },
  { title: 'Soft grey study', style: 'Casual', position: '0% 100%', tall: false, image: '/assets/discover/casual/casual-16.jpg' },
];

const menLooks = [
  { title: 'Navy campus', style: 'Stockholm', position: '50% 50%', tall: true, image: '/assets/discover/men/stockholm/stockholm-01.jpg' },
  { title: 'Silver morning', style: 'Stockholm', position: '50% 50%', tall: false, image: '/assets/discover/men/stockholm/stockholm-02.jpg' },
  { title: 'Ivory north', style: 'Stockholm', position: '50% 50%', tall: true, image: '/assets/discover/men/stockholm/stockholm-03.jpg' },
  { title: 'Sage weekend', style: 'Stockholm', position: '50% 50%', tall: false, image: '/assets/discover/men/stockholm/stockholm-04.jpg' },
  { title: 'Midnight polo', style: 'Stockholm', position: '50% 50%', tall: true, image: '/assets/discover/men/stockholm/stockholm-05.jpg' },
  { title: 'Blue essentials', style: 'Stockholm', position: '50% 50%', tall: false, image: '/assets/discover/men/stockholm/stockholm-06.jpg' },
  { title: 'Santorini navy', style: 'Stockholm', position: '50% 50%', tall: true, image: '/assets/discover/men/stockholm/stockholm-07.jpg' },
  { title: 'Nordic scholar', style: 'Stockholm', position: '50% 50%', tall: false, image: '/assets/discover/men/stockholm/stockholm-08.jpg' },
  { title: 'Black frost', style: 'Stockholm', position: '50% 50%', tall: true, image: '/assets/discover/men/stockholm/stockholm-09.jpg' },
  { title: 'Polo bear day', style: 'Stockholm', position: '50% 50%', tall: false, image: '/assets/discover/men/stockholm/stockholm-10.jpg' },
  { title: 'Ivory midnight', style: 'Stockholm', position: '50% 50%', tall: true, image: '/assets/discover/men/stockholm/stockholm-11.jpg' },
  { title: 'Grey Stockholm', style: 'Stockholm', position: '50% 50%', tall: false, image: '/assets/discover/men/stockholm/stockholm-12.jpg' },
  { title: 'Ivory Riviera', style: 'Old Money', position: '50% 50%', tall: true, image: '/assets/discover/men/old-money/old-money-01.jpg' },
  { title: 'Sage Society', style: 'Old Money', position: '50% 50%', tall: false, image: '/assets/discover/men/old-money/old-money-02.jpg' },
  { title: 'Espresso Leisure', style: 'Old Money', position: '50% 50%', tall: true, image: '/assets/discover/men/old-money/old-money-03.jpg' },
  { title: 'Cream Legacy', style: 'Old Money', position: '50% 50%', tall: false, image: '/assets/discover/men/old-money/old-money-04.jpg' },
  { title: 'Emerald Estate', style: 'Old Money', position: '50% 50%', tall: true, image: '/assets/discover/men/old-money/old-money-05.jpg' },
  { title: 'Camel Gentleman', style: 'Old Money', position: '50% 50%', tall: false, image: '/assets/discover/men/old-money/old-money-06.jpg' },
  { title: 'Alpine Navy', style: 'Old Money', position: '50% 50%', tall: true, image: '/assets/discover/men/old-money/old-money-07.jpg' },
  { title: 'Camel Sunday', style: 'Old Money', position: '50% 50%', tall: false, image: '/assets/discover/men/old-money/old-money-08.jpg' },
  { title: 'Riviera Club', style: 'Old Money', position: '50% 50%', tall: true, image: '/assets/discover/men/old-money/old-money-09.jpg' },
  { title: 'Burgundy Resort', style: 'Old Money', position: '50% 50%', tall: false, image: '/assets/discover/men/old-money/old-money-10.jpg' },
  { title: 'Heritage Bordeaux', style: 'Old Money', position: '50% 50%', tall: true, image: '/assets/discover/men/old-money/old-money-11.jpg' },
  { title: 'Cocoa Reserve', style: 'Old Money', position: '50% 50%', tall: false, image: '/assets/discover/men/old-money/old-money-12.jpg' },
  { title: 'Dark denim archive', style: 'Downtown', position: '50% 50%', tall: true, image: '/assets/discover/men/downtown/downtown-01.jpg' },
  { title: 'Brown campus', style: 'Downtown', position: '50% 50%', tall: false, image: '/assets/discover/men/downtown/downtown-02.jpg' },
  { title: 'Downtown classic', style: 'Downtown', position: '50% 50%', tall: true, image: '/assets/discover/men/downtown/downtown-03.jpg' },
  { title: 'Leather grunge', style: 'Downtown', position: '50% 50%', tall: false, image: '/assets/discover/men/downtown/downtown-04.jpg' },
  { title: 'Soft grey skate', style: 'Downtown', position: '50% 50%', tall: true, image: '/assets/discover/men/downtown/downtown-05.jpg' },
  { title: 'Striped city', style: 'Downtown', position: '50% 50%', tall: false, image: '/assets/discover/men/downtown/downtown-06.jpg' },
  { title: 'Scholar noir', style: 'Downtown', position: '50% 50%', tall: true, image: '/assets/discover/men/downtown/downtown-07.jpg' },
  { title: 'Olive downtown', style: 'Downtown', position: '50% 50%', tall: false, image: '/assets/discover/men/downtown/downtown-08.jpg' },
  { title: 'Graphic leather', style: 'Downtown', position: '50% 50%', tall: true, image: '/assets/discover/men/downtown/downtown-09.jpg' },
  { title: 'Washed city', style: 'Downtown', position: '50% 50%', tall: false, image: '/assets/discover/men/downtown/downtown-10.jpg' },
  { title: 'Cocoa street', style: 'Downtown', position: '50% 50%', tall: true, image: '/assets/discover/men/downtown/downtown-11.jpg' },
  { title: 'Corduroy weekend', style: 'Downtown', position: '50% 50%', tall: false, image: '/assets/discover/men/downtown/downtown-13.jpg' },
  { title: 'Green track energy', style: 'Street Style', position: '50% 50%', tall: true, image: '/assets/discover/men/street-style/street-style-01.jpg' },
  { title: 'Cream street classic', style: 'Street Style', position: '50% 50%', tall: false, image: '/assets/discover/men/street-style/street-style-02.jpg' },
  { title: 'Midnight graphic', style: 'Street Style', position: '50% 50%', tall: true, image: '/assets/discover/men/street-style/street-style-03.jpg' },
  { title: 'London red', style: 'Street Style', position: '50% 50%', tall: false, image: '/assets/discover/men/street-style/street-style-04.jpg' },
  { title: 'Union workwear', style: 'Street Style', position: '50% 50%', tall: true, image: '/assets/discover/men/street-style/street-style-05.jpg' },
  { title: 'Red terrace', style: 'Street Style', position: '50% 50%', tall: false, image: '/assets/discover/men/street-style/street-style-06.jpg' },
  { title: 'Brown skate layers', style: 'Street Style', position: '50% 50%', tall: true, image: '/assets/discover/men/street-style/street-style-07.jpg' },
  { title: 'Orange city pop', style: 'Street Style', position: '50% 50%', tall: false, image: '/assets/discover/men/street-style/street-style-08.jpg' },
  { title: 'Burgundy street', style: 'Street Style', position: '50% 50%', tall: true, image: '/assets/discover/men/street-style/street-style-09.jpg' },
  { title: 'Grey Supreme day', style: 'Street Style', position: '50% 50%', tall: false, image: '/assets/discover/men/street-style/street-style-10.jpg' },
  { title: 'Blue LA street', style: 'Street Style', position: '50% 50%', tall: true, image: '/assets/discover/men/street-style/street-style-11.jpg' },
  { title: 'Navy polo street', style: 'Street Style', position: '50% 50%', tall: false, image: '/assets/discover/men/street-style/street-style-12.jpg' },
  { title: 'Dr Pepper archive', style: 'Vintage', position: '50% 50%', tall: true, image: '/assets/discover/men/vintage/vintage-01.jpg' },
  { title: 'Eagle denim', style: 'Vintage', position: '50% 50%', tall: false, image: '/assets/discover/men/vintage/vintage-02.jpg' },
  { title: 'Corduroy winter archive', style: 'Vintage', position: '50% 50%', tall: true, image: '/assets/discover/men/vintage/vintage-03.jpg' },
  { title: 'Olive stripe archive', style: 'Vintage', position: '50% 50%', tall: false, image: '/assets/discover/men/vintage/vintage-04.jpg' },
  { title: 'Rust corduroy', style: 'Vintage', position: '50% 50%', tall: true, image: '/assets/discover/men/vintage/vintage-05.jpg' },
  { title: 'Forest winter layers', style: 'Vintage', position: '50% 50%', tall: false, image: '/assets/discover/men/vintage/vintage-06.jpg' },
  { title: 'Aviator workwear', style: 'Vintage', position: '50% 50%', tall: true, image: '/assets/discover/men/vintage/vintage-07.jpg' },
  { title: 'Burgundy rugby archive', style: 'Vintage', position: '50% 50%', tall: false, image: '/assets/discover/men/vintage/vintage-08.jpg' },
  { title: 'Leather heritage', style: 'Vintage', position: '50% 50%', tall: true, image: '/assets/discover/men/vintage/vintage-09.jpg' },
  { title: 'Plaid explorer', style: 'Vintage', position: '50% 50%', tall: false, image: '/assets/discover/men/vintage/vintage-10.jpg' },
  { title: 'Chocolate skater', style: 'Vintage', position: '50% 50%', tall: true, image: '/assets/discover/men/vintage/vintage-11.jpg' },
  { title: 'Grey school archive', style: 'Vintage', position: '50% 50%', tall: false, image: '/assets/discover/men/vintage/vintage-12.jpg' },
  { title: 'Cyber tie denim', style: 'Y2K', position: '50% 50%', tall: true, image: '/assets/discover/men/y2k/y2k-01.jpg' },
  { title: 'Blue tattoo skate', style: 'Y2K', position: '50% 50%', tall: false, image: '/assets/discover/men/y2k/y2k-02.jpg' },
  { title: 'Yellow rebel skate', style: 'Y2K', position: '50% 50%', tall: true, image: '/assets/discover/men/y2k/y2k-03.jpg' },
  { title: 'Electric blue Y2K', style: 'Y2K', position: '50% 50%', tall: false, image: '/assets/discover/men/y2k/y2k-04.jpg' },
  { title: 'Spider leather game', style: 'Y2K', position: '50% 50%', tall: true, image: '/assets/discover/men/y2k/y2k-05.jpg' },
  { title: 'Spider campus Y2K', style: 'Y2K', position: '50% 50%', tall: false, image: '/assets/discover/men/y2k/y2k-06.jpg' },
  { title: 'Monochrome skater', style: 'Y2K', position: '50% 50%', tall: true, image: '/assets/discover/men/y2k/y2k-07.jpg' },
  { title: 'Blue tribal skate', style: 'Y2K', position: '50% 50%', tall: false, image: '/assets/discover/men/y2k/y2k-08.jpg' },
  { title: 'Hello Kitty noir', style: 'Y2K', position: '50% 50%', tall: true, image: '/assets/discover/men/y2k/y2k-09.jpg' },
  { title: 'Subaru cyber', style: 'Y2K', position: '50% 50%', tall: false, image: '/assets/discover/men/y2k/y2k-10.jpg' },
  { title: 'Grey layered campus', style: 'Y2K', position: '50% 50%', tall: true, image: '/assets/discover/men/y2k/y2k-11.jpg' },
  { title: 'Silver anime track', style: 'Y2K', position: '50% 50%', tall: false, image: '/assets/discover/men/y2k/y2k-12.jpg' },
  { title: 'Ice blue varsity', style: 'Acubi', position: '50% 50%', tall: true, image: '/assets/discover/men/acubi/acubi-01.jpg' },
  { title: 'Stay wild monochrome', style: 'Acubi', position: '50% 50%', tall: false, image: '/assets/discover/men/acubi/acubi-02.jpg' },
  { title: 'Summer gasoline', style: 'Acubi', position: '50% 50%', tall: true, image: '/assets/discover/men/acubi/acubi-03.jpg' },
  { title: 'Blue star utility', style: 'Acubi', position: '50% 50%', tall: false, image: '/assets/discover/men/acubi/acubi-04.jpg' },
  { title: 'Midnight blue fusion', style: 'Acubi', position: '50% 50%', tall: true, image: '/assets/discover/men/acubi/acubi-05.jpg' },
  { title: 'Skull cargo layers', style: 'Acubi', position: '50% 50%', tall: false, image: '/assets/discover/men/acubi/acubi-06.jpg' },
  { title: 'Black silver racer', style: 'Acubi', position: '50% 50%', tall: true, image: '/assets/discover/men/acubi/acubi-07.jpg' },
  { title: 'Angel cargo day', style: 'Acubi', position: '50% 50%', tall: false, image: '/assets/discover/men/acubi/acubi-08.jpg' },
  { title: 'Saturn utility', style: 'Acubi', position: '50% 50%', tall: true, image: '/assets/discover/men/acubi/acubi-09.jpg' },
  { title: 'Green acubi campus', style: 'Acubi', position: '50% 50%', tall: false, image: '/assets/discover/men/acubi/acubi-10.jpg' },
  { title: 'Portugal ice blue', style: 'Acubi', position: '50% 50%', tall: true, image: '/assets/discover/men/acubi/acubi-11.jpg' },
  { title: 'Black star uniform', style: 'Acubi', position: '50% 50%', tall: false, image: '/assets/discover/men/acubi/acubi-12.jpg' },
  { title: 'Midnight city hoodie', style: 'Starboy', position: '50% 50%', tall: true, image: '/assets/discover/men/starboy/starboy-01.jpg' },
  { title: 'Black knit luxury', style: 'Starboy', position: '50% 50%', tall: false, image: '/assets/discover/men/starboy/starboy-02.jpg' },
  { title: 'Pressure leather night', style: 'Starboy', position: '50% 50%', tall: true, image: '/assets/discover/men/starboy/starboy-03.jpg' },
  { title: 'Silver car archive', style: 'Starboy', position: '50% 50%', tall: false, image: '/assets/discover/men/starboy/starboy-04.jpg' },
  { title: 'Emerald drive', style: 'Starboy', position: '50% 50%', tall: true, image: '/assets/discover/men/starboy/starboy-05.jpg' },
  { title: 'Leather tie contrast', style: 'Starboy', position: '50% 50%', tall: false, image: '/assets/discover/men/starboy/starboy-06.jpg' },
  { title: 'Oud black leather', style: 'Starboy', position: '50% 50%', tall: true, image: '/assets/discover/men/starboy/starboy-07.jpg' },
  { title: 'Soft black reserve', style: 'Starboy', position: '50% 50%', tall: false, image: '/assets/discover/men/starboy/starboy-08.jpg' },
  { title: 'Burgundy night', style: 'Starboy', position: '50% 50%', tall: true, image: '/assets/discover/men/starboy/starboy-10.jpg' },
  { title: 'Chocolate midnight', style: 'Starboy', position: '50% 50%', tall: false, image: '/assets/discover/men/starboy/starboy-11.jpg' },
  { title: 'Yankees silver lounge', style: 'Starboy', position: '50% 50%', tall: true, image: '/assets/discover/men/starboy/starboy-12.jpg' },
  { title: 'Saint Tears leather', style: 'Starboy', position: '50% 50%', tall: false, image: '/assets/discover/men/starboy/starboy-13.jpg' },
  { title: 'Check shirt casual', style: 'Casual', position: '50% 50%', tall: true, image: '/assets/discover/men/casual/casual-01.jpg' },
  { title: 'Duck graphic day', style: 'Casual', position: '50% 50%', tall: false, image: '/assets/discover/men/casual/casual-02.jpg' },
  { title: 'Navy wave basics', style: 'Casual', position: '50% 50%', tall: true, image: '/assets/discover/men/casual/casual-03.jpg' },
  { title: 'Grey polo ease', style: 'Casual', position: '50% 50%', tall: false, image: '/assets/discover/men/casual/casual-04.jpg' },
  { title: 'Grey comfort set', style: 'Casual', position: '50% 50%', tall: true, image: '/assets/discover/men/casual/casual-05.jpg' },
  { title: 'Charcoal everyday', style: 'Casual', position: '50% 50%', tall: false, image: '/assets/discover/men/casual/casual-06.jpg' },
  { title: 'Ivory knit balance', style: 'Casual', position: '50% 50%', tall: true, image: '/assets/discover/men/casual/casual-07.jpg' },
  { title: 'Cardigan denim day', style: 'Casual', position: '50% 50%', tall: false, image: '/assets/discover/men/casual/casual-08.jpg' },
  { title: 'Brown campus casual', style: 'Casual', position: '50% 50%', tall: true, image: '/assets/discover/men/casual/casual-09.jpg' },
  { title: 'Polo city basic', style: 'Casual', position: '50% 50%', tall: false, image: '/assets/discover/men/casual/casual-10.jpg' },
  { title: 'Green stripe day', style: 'Casual', position: '50% 50%', tall: true, image: '/assets/discover/men/casual/casual-11.jpg' },
  { title: 'Navy stripe basics', style: 'Casual', position: '50% 50%', tall: false, image: '/assets/discover/men/casual/casual-12.jpg' },
];

const allLooks = [...looks, ...menLooks];

const discoverStyles = ['For you', 'Stockholm', 'Downtown', 'Y2K', 'Old Money', 'Clean Girl', 'Street Style', 'Vintage', 'Coquette', 'Casual'];
const menDiscoverStyles = ['For you', 'Stockholm', 'Old Money', 'Downtown', 'Street Style', 'Vintage', 'Y2K', 'Acubi', 'Starboy', 'Casual'];

const russianLookTitles: Record<string, string> = {
  'Midnight Archive': 'Полуночный архив',
  'Coffee Workshop': 'Кофейная мастерская',
  'Campus Courier': 'Университетский курьер',
  'Analog Leather': 'Аналоговая кожа',
  'Shadow Knit': 'Теневой трикотаж',
  'Brown Pinstripe': 'Коричневая полоска',
  'Library Cardigan': 'Библиотечный кардиган',
  'Olive Studio': 'Оливковая студия',
  'Retro Static': 'Ретро-сигнал',
  'Asphalt Utility': 'Городской асфальт',
  'Cocoa Winter': 'Шоколадная зима',
  'Brown Borough': 'Коричневый район',
  'Corduroy Session': 'Вельветовая сессия',
  'Navy campus': 'Синий кампус', 'Silver morning': 'Серебряное утро', 'Ivory north': 'Молочный север',
  'Sage weekend': 'Шалфейный выходной', 'Midnight polo': 'Полуночное поло', 'Blue essentials': 'Синие основы',
  'Santorini navy': 'Синий Санторини', 'Nordic scholar': 'Северный студент', 'Black frost': 'Чёрный мороз',
  'Polo bear day': 'День с мишкой Поло', 'Ivory midnight': 'Молочная полночь', 'Grey Stockholm': 'Серый Стокгольм',
  'Ivory Riviera': 'Светлая Ривьера', 'Sage Society': 'Шалфейный клуб', 'Espresso Leisure': 'Эспрессо на отдыхе',
  'Cream Legacy': 'Кремовое наследие', 'Emerald Estate': 'Изумрудное поместье', 'Camel Gentleman': 'Джентльмен в кэмеле',
  'Alpine Navy': 'Альпийский синий', 'Camel Sunday': 'Кэмеловое воскресенье', 'Riviera Club': 'Клуб на Ривьере',
  'Burgundy Resort': 'Бордовый курорт', 'Heritage Bordeaux': 'Бордовое наследие', 'Cocoa Reserve': 'Резерв какао',
  'Dark denim archive': 'Архив тёмного денима', 'Brown campus': 'Коричневый кампус', 'Downtown classic': 'Классика даунтауна',
  'Leather grunge': 'Кожаный гранж', 'Soft grey skate': 'Серый скейт', 'Striped city': 'Полосатый город',
  'Scholar noir': 'Тёмный студент', 'Olive downtown': 'Оливковый даунтаун', 'Graphic leather': 'Кожа с принтом',
  'Washed city': 'Выцветший город', 'Cocoa street': 'Шоколадная улица',
  'Corduroy weekend': 'Вельветовый выходной',
  'Green track energy': 'Зелёный спортивный акцент', 'Cream street classic': 'Светлая уличная классика', 'Midnight graphic': 'Полуночный принт',
  'London red': 'Красный Лондон', 'Union workwear': 'Британский ворквир', 'Red terrace': 'Красная терраса',
  'Brown skate layers': 'Коричневый скейт', 'Orange city pop': 'Оранжевый городской акцент', 'Burgundy street': 'Бордовая улица',
  'Grey Supreme day': 'Серый день Supreme', 'Blue LA street': 'Синий Лос-Анджелес', 'Navy polo street': 'Синее поло',
  'Dr Pepper archive': 'Архив Dr Pepper', 'Eagle denim': 'Орёл и деним', 'Corduroy winter archive': 'Вельветовый зимний архив',
  'Olive stripe archive': 'Оливковые полосы', 'Rust corduroy': 'Рыжий вельвет', 'Forest winter layers': 'Лесные зимние слои',
  'Aviator workwear': 'Рабочий авиатор', 'Burgundy rugby archive': 'Бордовое ретро-поло', 'Leather heritage': 'Кожаное наследие',
  'Plaid explorer': 'Исследователь в клетке', 'Chocolate skater': 'Шоколадный скейтер', 'Grey school archive': 'Серый школьный архив',
  'Cyber tie denim': 'Кибер-деним с галстуком', 'Blue tattoo skate': 'Синий тату-скейт', 'Yellow rebel skate': 'Жёлтый скейт-бунт',
  'Electric blue Y2K': 'Электрический синий Y2K', 'Spider leather game': 'Человек-паук и кожа', 'Spider campus Y2K': 'Кампус Человека-паука',
  'Monochrome skater': 'Монохромный скейтер', 'Blue tribal skate': 'Синий трайбл-скейт', 'Hello Kitty noir': 'Тёмный Hello Kitty',
  'Subaru cyber': 'Кибер Subaru', 'Grey layered campus': 'Серый многослойный кампус', 'Silver anime track': 'Серебряный аниме-трек',
  'Ice blue varsity': 'Ледяной голубой varsity', 'Stay wild monochrome': 'Монохром Stay Wild', 'Summer gasoline': 'Летний Gasoline',
  'Blue star utility': 'Синий звёздный утилити', 'Midnight blue fusion': 'Полуночный синий микс', 'Skull cargo layers': 'Карго с черепами',
  'Black silver racer': 'Чёрно-серебряный рейсер', 'Angel cargo day': 'Карго с ангелом', 'Saturn utility': 'Утилити Сатурн',
  'Green acubi campus': 'Зелёный Acubi-кампус', 'Portugal ice blue': 'Ледяная Португалия', 'Black star uniform': 'Чёрная звёздная форма',
  'Midnight city hoodie': 'Худи ночного города', 'Black knit luxury': 'Чёрный трикотажный люкс', 'Pressure leather night': 'Ночная кожа Pressure',
  'Silver car archive': 'Серебряный автоархив', 'Emerald drive': 'Изумрудная поездка', 'Leather tie contrast': 'Кожа и контрастный галстук',
  'Oud black leather': 'Чёрная кожа Oud', 'Soft black reserve': 'Мягкий чёрный резерв',
  'Burgundy night': 'Бордовая ночь', 'Chocolate midnight': 'Шоколадная полночь', 'Yankees silver lounge': 'Серебряный Yankees',
  'Saint Tears leather': 'Кожа Saint Tears',
  'Check shirt casual': 'Повседневная клетчатая рубашка', 'Duck graphic day': 'День с принтом утки', 'Navy wave basics': 'Синие базовые вещи',
  'Grey polo ease': 'Лёгкий серый образ', 'Grey comfort set': 'Серый комфортный комплект', 'Charcoal everyday': 'Графитовый повседневный',
  'Ivory knit balance': 'Светлый трикотаж', 'Cardigan denim day': 'Кардиган и деним', 'Brown campus casual': 'Коричневый кампус-кэжуал',
  'Polo city basic': 'Городское поло', 'Green stripe day': 'День в зелёную полоску', 'Navy stripe basics': 'Синяя полосатая база',
  'Chocolate layers': 'Шоколадные слои', 'Coffee and denim': 'Кофе и деним', 'Polka leather': 'Кожа в горошек',
  'Gallery afternoon': 'День в галерее', 'Cream and cocoa': 'Крем и какао', 'Soft ivory': 'Мягкий айвори',
  'Black and silver': 'Чёрное с серебром', 'Midnight glow': 'Полуночное сияние', 'Nordic winter': 'Северная зима',
  'Nordic cocoa': 'Северное какао', 'Golden braid': 'Золотая коса', 'Blue daydream': 'Голубая мечта',
  'Ivory ruffles': 'Молочные оборки', 'Cocoa mini': 'Какао мини', 'Midnight denim': 'Полуночный деним', 'Blush nordic': 'Розовый север',
  'After-school layers': 'После занятий', 'Burgundy city': 'Бордовый город', 'Leather and flare': 'Кожа и клёш',
  'Downtown comfort': 'Уютный даунтаун', 'Weekend layers': 'Слои выходного дня', 'Brown plaid mood': 'Шоколадная клетка',
  'Teal city knit': 'Бирюзовый городской трикотаж', 'Monkey charm': 'Талисман-обезьянка', 'Rose academy': 'Розовая академия',
  'Ivory city layers': 'Молочные городские слои', 'Plaid noir': 'Чёрная клетка', 'Striped teddy day': 'Полосатый день с мишкой',
  'Honey vintage': 'Медовый винтаж', 'Striped night': 'Полосатый вечер', 'Corduroy winter': 'Вельветовая зима', 'Downtown journal': 'Дневник даунтауна',
  'Pink rebel': 'Розовый бунт', 'Aqua pop': 'Бирюзовый акцент', 'Princess energy': 'Энергия принцессы',
  'Graphic denim': 'Деним с характером', 'Candy casual': 'Сладкий кэжуал',
  'Chasing stars': 'В погоне за звёздами', 'Silver fawn': 'Серебряный оленёнок', 'Preppy grunge': 'Преппи-гранж',
  'Guitar grey': 'Гитарный серый', 'Union rebel': 'Британский бунт', 'Pink archive': 'Розовый архив',
  'Crimson butterfly': 'Малиновая бабочка', 'Silver star denim': 'Серебряный звёздный деним', 'Blue cyber': 'Синий кибер', 'Burgundy star': 'Бордовая звезда',
  'New York star': 'Звезда Нью-Йорка',
  'Camel tailoring': 'Карамельный силуэт', 'Equestrian classic': 'Конная классика', 'Chocolate and ivory': 'Шоколад и айвори',
  'Burgundy heritage': 'Бордовое наследие', 'Cream investment': 'Кремовая классика', 'Navy polish': 'Безупречный синий',
  'Monochrome elegance': 'Монохромная элегантность',
  'Midnight baroque': 'Полуночное барокко', 'Italian espresso': 'Итальянский эспрессо', 'Riviera stripes': 'Полоски Ривьеры',
  'Heritage plaid': 'Наследие в клетку', 'Gilded corset': 'Позолоченный корсет', 'Vanilla reserve': 'Ванильный резерв',
  'Leopard tailoring': 'Леопардовый силуэт', 'Navy maison': 'Тёмно-синий модный дом', 'Black reserve': 'Чёрный резерв',
  'Pink lounge': 'Розовый уют', 'Blush denim': 'Румяный деним', 'Everyday neutral': 'Нейтральный день',
  'Soft morning': 'Нежное утро', 'Cozy clean': 'Чистый уют', 'Pink and denim': 'Розовый и деним', 'Simple essentials': 'Простые основы',
  'Navy clean street': 'Чистый синий стрит', 'Grey reset': 'Серая перезагрузка', 'Silver wellness': 'Серебряный велнес',
  'Pink pilates': 'Розовый пилатес', 'Blush campus': 'Розовый кампус', 'Silver braid': 'Серебряная коса',
  'Blue bunny morning': 'Утро с голубым зайчиком', 'Quiet grey basics': 'Спокойная серая база',
  'Vanilla ease': 'Ванильная лёгкость',
  'Red campus': 'Красный кампус', 'Polo and denim': 'Поло и деним', 'Yellow statement': 'Солнечный акцент',
  'Cherry sport': 'Вишнёвый спорт', 'Denim and red': 'Деним и красный',
  'Pink street set': 'Розовый стрит', 'Burgundy skate': 'Бордовый скейт', 'Grey street layers': 'Серые городские слои',
  'Black gold track': 'Чёрно-золотой трек', 'Spider campus': 'Паучий кампус', 'Green terrace': 'Зелёная терраса',
  'Burgundy jersey': 'Бордовая форма', 'Racing scarf': 'Гоночный платок', 'Gold denim maxi': 'Золотой деним макси',
  'New York blue': 'Синий Нью-Йорк', 'Union denim': 'Британский деним',
  'Brown flare': 'Шоколадный клёш', 'Plaid nostalgia': 'Клетчатая ностальгия', 'Corduroy lace': 'Вельвет и кружево',
  'Printed denim': 'Узорный деним', 'Romantic archive': 'Романтика из архива', 'Chocolate leather': 'Шоколадная кожа',
  'Retro traveler': 'Ретро-путешествие', 'Autumn archive': 'Осенний архив',
  'Retro brunette': 'Ретро-брюнетка', 'Cocoa flare': 'Какао и клёш', 'Leather modernist': 'Кожаный модерн',
  'Polka afternoon': 'Горошек после полудня', 'Plaid road trip': 'Клетчатое путешествие',
  'Midnight polka': 'Полночный горошек', 'Corset archive': 'Корсет из архива',
  'Cocoa weekend': 'Шоколадный выходной',
  'Pearl and lace': 'Жемчуг и кружево', 'Soft neutral': 'Нежный нейтральный', 'Blush lounge': 'Розовый отдых',
  'Pink daydream': 'Розовая мечта', 'Pink polka': 'Розовый горошек', 'Floral pastel': 'Цветочная пастель', 'Winter ribbon': 'Зимняя лента',
  'Blush bellbottoms': 'Румяный клёш', 'Pink snow day': 'Розовый снежный день', 'Shoujo ribbons': 'Банты сёдзё',
  'Babydoll noir': 'Кукольный нуар', 'Crystal hearts': 'Хрустальные сердца', 'Parisian doll': 'Парижская куколка',
  'Strawberry cream': 'Клубничный крем', 'Miffy schoolgirl': 'Школьница Миффи', 'Ribbon diary': 'Дневник с бантом',
  'Navy everyday': 'Синий на каждый день', 'Coffee basics': 'Кофейная база', 'Weekend stripe': 'Полоска выходного дня',
  'Soft layers': 'Мягкие слои', 'Bookshop afternoon': 'День в книжном', 'Chocolate hoodie': 'Шоколадное худи',
  'Cozy neutral': 'Уютный нейтральный', 'Burgundy knit': 'Бордовый трикотаж', 'Leather weekend': 'Кожаные выходные',
  'Leather and sambas': 'Кожа и самбы', 'Cherry keychain': 'Вишнёвый брелок', 'Cocoa stripe': 'Полоска какао',
  'Pistachio denim': 'Фисташковый деним', 'Library layers': 'Слои для библиотеки', 'Cherry dots': 'Вишнёвый горошек',
  'Soft grey study': 'Мягкая серая учёба',
};

export function DiscoverPage() {
  const { language } = useLanguage();
  const { gender } = useProfileGender();
  const tr = (en: string, ru: string) => localize(language, en, ru);
  const [filter, setFilter] = useState('For you');
  const [saved, setSaved] = useState<string[]>(() => allLooks.filter((look) => isLookSaved(`idea-${look.title}`)).map((look) => look.title));
  const [searching, setSearching] = useState(false);
  const [query, setQuery] = useState('');
  const availableStyles = gender === 'female' ? discoverStyles : menDiscoverStyles;
  const genderLooks = gender === 'female' ? looks : menLooks;
  const visible = genderLooks.filter((look) => (filter === 'For you' || look.style === filter) && `${look.title} ${look.style}`.toLowerCase().includes(query.toLowerCase()));
  function save(look: typeof looks[number]) {
    const kept = toggleSavedLook({ id: `idea-${look.title}`, style: look.style, items: [], image: look.image, category: 'idea', title: look.title, gender });
    setSaved(kept ? [...saved, look.title] : saved.filter((item) => item !== look.title));
  }

  return <div className="stack-lg fade-in">
    <section className="page-title"><div><p className="eyebrow">{tr('Curated for your DNA','Подобрано по твоему стилю')}</p><h1>{tr('Discover','Идеи')}</h1></div><button className="circle-button" onClick={() => setSearching(!searching)} aria-label={tr('Search','Поиск')}><Icon name={searching ? 'close' : 'search'} /></button></section>
    {searching && <div className="search-box"><Icon name="search" size={19} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={tr('Search inspiration','Искать вдохновение')} autoFocus /></div>}
    <div className="chip-row discover-filters">{availableStyles.map((item) => <button className={filter === item ? 'chip active' : 'chip'} onClick={() => setFilter(item)} key={item}>{styleLabel(item, language)}</button>)}</div>
    <section className="masonry">{visible.map((look) => <article className={look.tall ? 'discover-card tall' : 'discover-card'} key={look.title}><FashionImage position={look.position} src={look.image} /><button className={saved.includes(look.title) ? 'saved' : ''} onClick={() => save(look)} aria-label={tr('Save look','Сохранить образ')}><Icon name="heart" size={19} /></button><div><p>{styleLabel(look.style, language)}</p><h3>{language === 'ru' ? russianLookTitles[look.title] : look.title}</h3><Link href={`/create?mode=recreate&style=${encodeURIComponent(look.style)}&image=${encodeURIComponent(look.image)}`}>{tr('Recreate look','Повторить образ')} <Icon name="arrow" size={15} /></Link></div></article>)}</section>
    {visible.length === 0 && <div className="empty-state"><Icon name="upload" /><h3>{gender === 'male' ? tr('Add looks for this style', 'Добавь образы для этого стиля') : tr('Looks coming soon','Образы скоро появятся')}</h3><p>{gender === 'male' ? tr('Send images and they will appear in this men’s style section.', 'Пришли изображения, и они появятся в этом разделе мужского стиля.') : tr('Add inspiration images for this style.','Добавьте изображения для этого стиля.')}</p></div>}
  </div>;
}
